export const anaheimDucks = [
  {
        "Name": "Ryan Getzlaf",
        "Number": "15",
        "Position": "Center",
        "Birthplace": "Regina, SK, CAN",
        "Born": "May 10, 1985",
        "Age": "33",
        "Height": "6'4",
        "Weight": "225 lb",
        "Shoots": "Right",
        "Awards": "Stanley Cup 2006-2007 Anaheim Ducks",
        "Draft": "2003 ANA, 1st rd, 19th pk",
        "Salary": "$8,950,000",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/thumb/c/cf/Flag_of_Canada.svg/1280px-Flag_of_Canada.svg.png",
        "Summary": "13 G, 34 A, 47 P",
        "Highlights": "https://www.youtube.com/watch?v=8vLD68-dPKw",
    },
    {
        "Name": "Derek Grant",
        "Number": "38",
        "Position": "Center",
        "Birthplace": "Abbotsford, BC, CAN",
        "Born": "April 20, 1990",
        "Age": "28",
        "Height": "6'3",
        "Weight": "215 lb",
        "Shoots": "Left",
        "Awards": "N/A",
        "Draft": "2008 OTT, 4th rd, 28th pk",
        "Salary": "$650,000",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/thumb/c/cf/Flag_of_Canada.svg/1280px-Flag_of_Canada.svg.png",
        "Summary": "2 G, 5 A, 7 P",
        "Highlights": "https://www.youtube.com/watch?v=19B3c3qCg0w"
    },
    {
        "Name": "Adam Henrique",
        "Number": "14",
        "Position": "Center",
        "Birthplace": "Brantford, ON, CAN",
        "Born": "February 6, 1990",
        "Age": "29",
        "Height": "6'0",
        "Weight": "197 lb",
        "Shoots": "Left",
        "Awards": "N/A",
        "Draft": "2008 NJD, 3rd rd, 21st pk",
        "Salary": "$5,500,000",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/thumb/c/cf/Flag_of_Canada.svg/1280px-Flag_of_Canada.svg.png",
        "Summary": "18 G, 23 A, 41 P",
        "Highlights": "https://www.nhl.com/ducks/video/henrique-buries-beauty-on-rush/t-277437084/c-67004903"
    },
    {
        "Name": "Max Jones",
        "Number": "49",
        "Position": "LW",
        "Birthplace": "Rochester, MI, USA",
        "Born": "February 6, 1990",
        "Age": "21",
        "Height": "6'3",
        "Weight": "220 lb",
        "Shoots": "Left",
        "Awards": "N/A",
        "Draft": "2016 ANA, 1st rd, 24th pk",
        "Salary": "$925,000",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/1280px-Flag_of_the_United_States.svg.png",
        "Summary": "1 G, 1 A, 2 P",
        "Highlights": "https://www.nhl.com/ducks/video/jones-first-career-goal/t-277437084/c-66690703",
    },
    {
        "Name": "Ondrej Kase",
        "Number": "25",
        "Position": "RW",
        "Birthplace": "Kadan, CZE",
        "Born": "November 8, 1995",
        "Age": "23",
        "Height": "5'11",
        "Weight": "186 lb",
        "Shoots": "Right",
        "Awards": "N/A",
        "Draft": "2014 ANA, 7th rd, 25th pk",
        "Salary": "$2,600,000",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_Czech_Republic.svg/255px-Flag_of_the_Czech_Republic.svg.png",
        "Summary": "11 G, 9 A, 20 P",
        "Highlights": "https://www.nhl.com/ducks/video/kase-finishes-the-hat-trick/t-277437084/c-63898803",
    },
    {
        "Name": "Ryan Kesler",
        "Number": "17",
        "Position": "Center",
        "Birthplace": "Livonia, MI, USA",
        "Born": "August 31, 1984",
        "Age": "34",
        "Height": "6'2",
        "Weight": "206 lb",
        "Shoots": "Right",
        "Awards": "Frank J. Selke Trophy 2010-2011 Vancouver Canucks",
        "Draft": "2003 VAN, 1st rd, 23rd pk",
        "Salary": "$6,675,000",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/1280px-Flag_of_the_United_States.svg.png",
        "Summary": "5 G, 3 A, 8 P",
        "Highlights": "https://www.nhl.com/ducks/video/kesler-pots-insurance-goal/t-277437084/c-66039403",
    },
    {
        "Name": "Corey Perry",
        "Number": "10",
        "Position": "RW",
        "Birthplace": "Peterborough, ON, CAN",
        "Born": "May 16, 1985",
        "Age": "33",
        "Height": "6'3",
        "Weight": "206 lb",
        "Shoots": "Right",
        "Awards": "Stanley Cup 2006-2007 Anaheim Ducks, Hart Memorial Trophy 2010-2011 Anaheim Ducks, Maurice Richard Trophy 2010-2011 Anaheim Ducks",
        "Draft": "2003 ANA, 1st rd, 28th pk",
        "Salary": "$9,000,000",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/thumb/c/cf/Flag_of_Canada.svg/1280px-Flag_of_Canada.svg.png",
        "Summary": "5 G, 4 A, 9 P",
        "Highlights": "https://www.nhl.com/ducks/video/perry-delivers-in-the-clutch/t-277437084/c-66947803",
    },
    {
        "Name": "Rickard Rakell",
        "Number": "67",
        "Position": "LW",
        "Birthplace": "Sundbyberg, SWE",
        "Born": "May 5, 1993",
        "Age": "25",
        "Height": "6'1",
        "Weight": "202 lb",
        "Shoots": "Right",
        "Awards": "N/A",
        "Draft": "2011 ANA, 1st rd, 30th pk",
        "Salary": "$3,800,000",
        "Flag": "http://flags.fmcdn.net/data/flags/w580/se.png",
        "Summary": "15 G, 23 A, 38 P",
        "Highlights": "https://www.nhl.com/ducks/video/rakells-second-goal-of-the-game/t-277437084/c-67135103",
    },
    {
        "Name": "Nick Ritchie",
        "Number": "37",
        "Position": "LW",
        "Birthplace": "Orangeville, ON, CAN",
        "Born": "December 5, 1995",
        "Age": "23",
        "Height": "6'2",
        "Weight": "206 lb",
        "Shoots": "Left",
        "Awards": "N/A",
        "Draft": "2014 ANA, 1st rd, 10th pk",
        "Salary": "$1,200,000",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/thumb/c/cf/Flag_of_Canada.svg/1280px-Flag_of_Canada.svg.png",
        "Summary": "9 G, 22 A, 31 P",
        "Highlights": "https://www.nhl.com/ducks/video/ritchie-jams-home-opening-goal/t-277437084/c-66625703",
    },
    {
        "Name": "Carter Rowney",
        "Number": "24",
        "Position": "Center",
        "Birthplace": "Grand Prairie, AB, CAN",
        "Born": "May 10, 1989",
        "Age": "29",
        "Height": "6'2",
        "Weight": "206 lb",
        "Shoots": "Right",
        "Awards": "Stanley Cup 2016-2017 Pittsburgh Penguins",
        "Draft": "N/A",
        "Salary": "$1,400,000",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/thumb/c/cf/Flag_of_Canada.svg/1280px-Flag_of_Canada.svg.png",
        "Summary": "6 G, 11 A, 17 P",
        "Highlights": "https://www.nhl.com/ducks/video/rowney-puts-ducks-ahead-with-shg/t-277437084/c-67174403",
    },
    {
        "Name": "Kiefer Sherwood",
        "Number": "64",
        "Position": "RW",
        "Birthplace": "Columbus, OH, USA",
        "Born": "March 31, 1995",
        "Age": "23",
        "Height": "6'0",
        "Weight": "194 lb",
        "Shoots": "Right",
        "Awards": "N/A",
        "Draft": "N/A",
        "Salary": "$925,000",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/1280px-Flag_of_the_United_States.svg.png",
        "Summary": "6 G, 6 A, 12 P",
        "Highlights": "https://www.nhl.com/ducks/video/sherwood-nets-quick-wrister/t-277437084/c-67245703",
    },
    {
        "Name": "Devin Shore",
        "Number": "29",
        "Position": "Center",
        "Birthplace": "Ajax, ON, CAN",
        "Born": "July 19, 1994",
        "Age": "24",
        "Height": "6'1",
        "Weight": "205 lb",
        "Shoots": "Left",
        "Awards": "N/A",
        "Draft": "2012 DAL, 2nd rd, 31st pk",
        "Salary": "$2,200,000",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/thumb/c/cf/Flag_of_Canada.svg/1280px-Flag_of_Canada.svg.png",
        "Summary": "4 G, 4 A, 8 P",
        "Highlights": "https://www.nhl.com/ducks/video/shore-taps-in-a-shorthanded-goal/t-277437084/c-66358403",
    },
    {
        "Name": "Jakob Silfverberg",
        "Number": "33",
        "Position": "RW",
        "Birthplace": "Gävle, SWE",
        "Born": "October 13, 1990",
        "Age": "28",
        "Height": "6'1",
        "Weight": "204 lb",
        "Shoots": "Right",
        "Awards": "N/A",
        "Draft": "2009 OTT, 2nd rd, 9th pk",
        "Salary": "$3,750,000",
        "Flag": "http://flags.fmcdn.net/data/flags/w580/se.png",
        "Summary": "23 G, 15 A, 38 P",
        "Highlights": "https://www.nhl.com/ducks/video/silfverbergs-overtime-winner/t-277437084/c-67135303",
    },
    {
        "Name": "Daniel Sprong",
        "Number": "11",
        "Position": "RW",
        "Birthplace": "Amsterdam, NLD",
        "Born": "March 17, 1997",
        "Age": "22",
        "Height": "6'0",
        "Weight": "180 lb",
        "Shoots": "Right",
        "Awards": "N/A",
        "Draft": "2015 PTT, 2nd rd, 16th pk",
        "Salary": "$750,000",
        "Flag": "https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg",
        "Summary": "13 G, 5 A, 18 P",
        "Highlights": "https://www.nhl.com/ducks/video/sprongs-pretty-backhand-goal/t-277437084/c-66793603",
    },
    {
        "Name": "Sam Steel",
        "Number": "34",
        "Position": "Center",
        "Birthplace": "Ardrossan, AB, CAN",
        "Born": "February 3, 1998",
        "Age": "21",
        "Height": "5'11",
        "Weight": "186 lb",
        "Shoots": "Left",
        "Awards": "N/A",
        "Draft": "2016 ANA, 1st rd, 30th pk",
        "Salary": "$925,000",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/thumb/c/cf/Flag_of_Canada.svg/1280px-Flag_of_Canada.svg.png",
        "Summary": "4 G, 4 A, 8 P",
        "Highlights": "https://www.nhl.com/ducks/video/steel-completes-hat-trick/t-277437084/c-67243603",
    },
    {
        "Name": "Troy Terry",
        "Number": "61",
        "Position": "RW",
        "Birthplace": "Denver, CO, USA",
        "Born": "September 10, 1997",
        "Age": "21",
        "Height": "6'1",
        "Weight": "178 lb",
        "Shoots": "Right",
        "Awards": "N/A",
        "Draft": "2015 ANA, 5th rd, 27th pk",
        "Salary": "$925,000",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/1280px-Flag_of_the_United_States.svg.png",
        "Summary": "4 G, 9 A, 13 P",
        "Highlights": "https://www.youtube.com/watch?v=zrVsZzNDDM8",
    },
    {
        "Name": "Cam Fowler",
        "Number": "4",
        "Position": "Defense",
        "Birthplace": "Windsor, ON, CAN",
        "Born": "December 5, 1991",
        "Age": "27",
        "Height": "6'2",
        "Weight": "206 lb",
        "Shoots": "Left",
        "Awards": "N/A",
        "Draft": "2010 ANA, 1st rd, 12th pk",
        "Salary": "$7,500,000",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/thumb/c/cf/Flag_of_Canada.svg/1280px-Flag_of_Canada.svg.png",
        "Summary": "5 G, 16 A, 21 P",
        "Highlights": "https://www.nhl.com/ducks/video/fowlers-power-play-goal/t-277437084/c-66541703",
    },
    {
        "Name": "Brendan Guhle",
        "Number": "2",
        "Position": "Defense",
        "Birthplace": "Edmonton, AB, CAN",
        "Born": "July 29, 1997",
        "Age": "21",
        "Height": "6'2",
        "Weight": "196 lb",
        "Shoots": "Left",
        "Awards": "N/A",
        "Draft": "2015 BUF, 2nd rd, 21st pk",
        "Salary": "$650,000",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/thumb/c/cf/Flag_of_Canada.svg/1280px-Flag_of_Canada.svg.png",
        "Summary": "0 G, 1 A, 1 P",
        "Highlights": "2014-12-15T12:31:42.547000Z",
    },
    {
        "Name": "Korbinian Holzer",
        "Number": "5",
        "Position": "Defense",
        "Birthplace": "Munich, DEU",
        "Born": "February 16, 1997",
        "Age": "31",
        "Height": "6'3",
        "Weight": "218 lb",
        "Shoots": "Right",
        "Awards": "N/A",
        "Draft": "2006 TOR, 4th rd, 18th pk",
        "Salary": "$900,000",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/1280px-Flag_of_Germany.svg.png",
        "Summary": "0 G, 2 A, 2 P",
        "Highlights": "https://www.nhl.com/ducks/video/getzlaf-holzer-team-up-for-goal/t-277437084/c-51069103",
    },
    {
        "Name": "Jacob Larsson",
        "Number": "32",
        "Position": "Defense",
        "Birthplace": "Ljungby, SWE",
        "Born": "April 29, 1997",
        "Age": "21",
        "Height": "6'2",
        "Weight": "197 lb",
        "Shoots": "Left",
        "Awards": "N/A",
        "Draft": "2015 ANA, 1st rd, 27th pk",
        "Salary": "$925,000",
        "Flag": "http://flags.fmcdn.net/data/flags/w580/se.png",
        "Summary": "0 G, 5 A, 5 P",
        "Highlights": "2014-12-15T12:31:42.547000Z",
    },
    {
        "Name": "Hampus Lindholm",
        "Number": "47",
        "Position": "Defense",
        "Birthplace": "Helsingborg, SWE",
        "Born": "January 20, 1994",
        "Age": "25",
        "Height": "6'3",
        "Weight": "211 lb",
        "Shoots": "Left",
        "Awards": "N/A",
        "Draft": "2012 ANA, 1st rd, 6th pk",
        "Salary": "$6,750,000",
        "Flag": "http://flags.fmcdn.net/data/flags/w580/se.png",
        "Summary": "6 G, 20 A, 26 P",
        "created": "2014-12-15T12:31:42.547000Z",
        "edited": "2017-04-19T10:56:06.685592Z",
        "url": "https://swapi.co/api/starships/15/"
    },
    {
        "Name": "Josh Manson",
        "Number": "42",
        "Position": "Defense",
        "Birthplace": "Hinsdale, IL, USA",
        "Born": "October 7, 1991",
        "Age": "27",
        "Height": "6'3",
        "Weight": "216 lb",
        "Shoots": "Right",
        "Awards": "N/A",
        "Draft": "2011 ANA, 6th rd, 9th pk",
        "Salary": "$3,250,000",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/1280px-Flag_of_the_United_States.svg.png",
        "Summary": "3 G, 13 A, 16 P",
        "created": "2014-12-15T12:31:42.547000Z",
        "edited": "2017-04-19T10:56:06.685592Z",
        "url": "https://swapi.co/api/starships/15/"
    },
    {
        "Name": "Jaycob Megna",
        "Number": "43",
        "Position": "Defense",
        "Birthplace": "Plantation, FL, USA",
        "Born": "December 10, 1992",
        "Age": "26",
        "Height": "6'6",
        "Weight": "221 lb",
        "Shoots": "Left",
        "Awards": "N/A",
        "Draft": "2012 ANA, 7th rd, 29th pk",
        "Salary": "$650,000",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/1280px-Flag_of_the_United_States.svg.png",
        "Summary": "1 G, 3 A, 4 P",
        "created": "2014-12-15T12:31:42.547000Z",
        "edited": "2017-04-19T10:56:06.685592Z",
        "url": "https://swapi.co/api/starships/15/"
    },
    {
        "Name": "Andy Welinski",
        "Number": "45",
        "Position": "Defense",
        "Birthplace": "Duluth, MN, USA",
        "Born": "April 27, 1993",
        "Age": "25",
        "Height": "6'1",
        "Weight": "201 lb",
        "Shoots": "Right",
        "Awards": "N/A",
        "Draft": "2011 ANA, 3rd rd, 21st pk",
        "Salary": "$690,000",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/1280px-Flag_of_the_United_States.svg.png",
        "Summary": "0 G, 3 A, 3 P",
        "created": "2014-12-15T12:31:42.547000Z",
        "edited": "2017-04-19T10:56:06.685592Z",
        "url": "https://swapi.co/api/starships/15/"
    },
    {
        "Name": "John Gibson",
        "Number": "36",
        "Position": "Goalie",
        "Birthplace": "Pittsburgh, PA, USA",
        "Born": "July 14, 1993",
        "Age": "25",
        "Height": "6'2",
        "Weight": "206 lb",
        "Catches": "Left",
        "Awards": "William M. Jennings Trophy 2015-2016 Anaheim Ducks",
        "Draft": "2011 ANA, 2nd rd, 9th pk",
        "Salary": "$3,300,000",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/1280px-Flag_of_the_United_States.svg.png",
        "Summary": "24-22-8, 2.89 GAA",
        "created": "2014-12-15T12:31:42.547000Z",
        "edited": "2017-04-19T10:56:06.685592Z",
        "url": "https://swapi.co/api/starships/15/"
    },
    {
        "Name": "Chad Johnson",
        "Number": "1",
        "Position": "Goalie",
        "Birthplace": "Saskatoon, SK, CAN",
        "Born": "June 10, 1986",
        "Age": "32",
        "Height": "6'3",
        "Weight": "197 lb",
        "Catches": "Left",
        "Awards": "N/A",
        "Draft": "2006 PIT, 5th rd, 2nd pk",
        "Salary": "$1,750,000",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/thumb/c/cf/Flag_of_Canada.svg/1280px-Flag_of_Canada.svg.png",
        "Summary": "0-5-0, 3.75 GAA",
        "created": "2014-12-15T12:31:42.547000Z",
        "edited": "2017-04-19T10:56:06.685592Z",
        "url": "https://swapi.co/api/starships/15/"
    },
    {
        "Name": "Ryan Miller",
        "Number": "30",
        "Position": "Goalie",
        "Birthplace": "East Lansing, MI, USA",
        "Born": "July 17, 1980",
        "Age": "38",
        "Height": "6'2",
        "Weight": "168 lb",
        "Catches": "Left",
        "Awards": "Vezina Trophy 2009-2010 Buffalo Sabres, NHL Foundation Player Award, 2009-2019 Buffalo Sabres",
        "Draft": "1999 BUF, 5th rd, 12th pk",
        "Salary": "$2,000,000",
        "Flag": "https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/1280px-Flag_of_the_United_States.svg.png",
        "Summary": "7-6-2, 2.67 GAA",
        "created": "2014-12-15T12:31:42.547000Z",
        "edited": "2017-04-19T10:56:06.685592Z",
        "url": "https://swapi.co/api/starships/15/"
    },
]